AllCops:
  TargetRubyVersion: 2.5

# === Style rules =============
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# === Lint rules
Lint/UriEscapeUnescape:
  Enabled: false

# === Metrics rules ===========
Metrics:
  Enabled: false

# === Layout rules ============
Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# === Naming rules ============
Naming/AccessorMethodName:
  Enabled: false
